name: Staging deploy

on:
  push:
    branches: ["develop"]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME || github.actor }}
          password: ${{ secrets.CR_PAT || secrets.GITHUB_TOKEN }}

      - name: Build Server Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/checkmate-backend:staging \
            -f ./docker/staging/server.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            .

      - name: Push Server Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/checkmate-backend:staging

      - name: Build Mongo Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/checkmate-mongo:staging \
            -f ./docker/staging/mongoDB.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            .

      - name: Push MongoDB Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/checkmate-mongo:staging

      - name: Build Redis Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/checkmate-redis:staging \
            -f ./docker/staging/redis.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            .

      - name: Push Redis Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/checkmate-redis:staging

  deploy-to-staging:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and restart container using Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd checkmate/server/docker/staging
            docker compose down
            docker compose pull
            docker compose up -d
